server:
    extraSecretEnvironmentVars:
        - envName: AWS_DEFAULT_REGION
          secretName: "vault-aws-kms-secrets"
          secretKey: "region"
        - envName: AWS_ACCESS_KEY_ID
          secretName: "vault-aws-kms-secrets"
          secretKey: "access-key"
        - envName: AWS_SECRET_ACCESS_KEY
          secretName: "vault-aws-kms-secrets"
          secretKey: "access-key-secret"
        - envName: VAULT_AWSKMS_SEAL_KEY_ID
          secretName: "vault-aws-kms-secrets"
          secretKey: "kms-id"
        - envName: AWS_DYNAMODB_TABLE
          secretName: "vault-aws-kms-secrets"
          secretKey: "table"

    authDelegator:
        enabled: true
    ha:
        enabled: true
        replicas: 3
        config: |
            ui = true
            api_addr = "http://POD_ID:8200"
            seal "awskms" {}
            listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
            }
            storage "dynamodb" {
                ha_enabled = "true"
            }
injector:
    enabled: false
